[package]
name = "please-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.4", features = ["derive", "cargo"] }
directories-next = "2.0.0"
pickledb = { path = "../../pickledb-rs" }
serde = { version = "1.0.137", features = ["derive"] }
tegen = "0.1.4"
term-table = "1.3.2"
time = { version = "0.3.9", features = [
    "serde",
    "std",
    "local-offset",
    "formatting",
] }
yansi = "0.5.1"
