[package]
name = "please"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8" }
directories-next = "2.0.0"
pickledb = { git = "https://github.com/sigaloid/pickledb-rs" }
serde = { version = "1.0.138" }
tegen = "0.1.4"
term-table = "1.3.2"
time = { version = "0.3.11", features = ["local-offset", "formatting"] }
yansi = "0.5.1" 
casual = "0.2"
ureq = { version = "2.4.0" }

[profile.release]
# strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
