use pickledb::PickleDb;

const QUOTE_COUNT: usize = 501;

static QUOTES: [&str; QUOTE_COUNT] = [
    "Beware of missing chances; otherwise it may be altogether too late some day. ~ Franz Liszt",
    "The way we communicate with others and with ourselves ultimately determines the quality of our lives. ~ Tony Robbins",
    "No alibi will save you from accepting the responsibility. ~ Napoleon Hill",
    "There is more wisdom in your body than in your deepest philosophy. ~ Friedrich Nietzsche",
    "When you are content to be simply yourself and don't compare or compete, everybody will respect you. ~ Laozi",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. ~ Ralph Waldo Emerson",
    "Happiness can exist only in acceptance. ~ George Orwell",
    "The place to improve the world is first in one's own heart and head and hands. ~ Robert M. Pirsig",
    "I want you to be everything that's you, deep at the center of your being. ~ Confucius",
    "Motivation is the art of getting people to do what you want them to do because they want to do it. ~ Dwight D. Eisenhower",
    "Programs must be written for people to read, and only incidentally for machines to execute. ~ Hal Abelson",
    "The foolish man seeks happiness in the distance, the wise grows it under his feet. ~ James Oppenheim",
    "Don't wait. The time will never be just right. ~ Napoleon Hill",
    "Successful people ask better questions, and as a result, they get better answers. ~ Tony Robbins",
    "Impossibilities are merely things which we have not yet learned. ~ Charles W. Chesnutt",
    "The world is round and the place which may seem like the end may also be the beginning. ~ Ivy Baker Priest",
    "Thought is the blossom; language the bud; action the fruit behind it. ~ Ralph Waldo Emerson",
    "We don't receive wisdom; we must discover it for ourselves after a journey that no one can take for us or spare us. ~ Marcel Proust",
    "The power of intuitive understanding will protect you from harm until the end of your days. ~ Laozi",
    "Your sacred space is where you can find yourself again and again. ~ Joseph Campbell",
    "If you have the guts to keep making mistakes, your wisdom and intelligence leap forward with huge momentum. ~ Holly Near",
    "Value your friendship. Value your relationships. ~ Barbara Bush",
    "May our hearts garden of awakening bloom with hundreds of flowers. ~ Thích Nhất Hạnh",
    "Better be ignorant of a matter than half know it. ~ Publilius Syrus",
    "Never bend your head. Always hold it high. Look the world right in the eye. ~ Helen Keller",
    "Logic is the beginning of wisdom, not the end. ~ Leonard Nimoy",
    "No pessimist ever discovered the secrets of the stars, or sailed to an uncharted land, or opened a new heaven to the human spirit. ~ Helen Keller",
    "An idea that is developed and put into action is more important than an idea that exists only as an idea. ~ Buddha",
    "If the shoe doesn't fit, must we change the foot? ~ Gloria Steinem",
    "The greatest good you can do for another is not just share your riches, but reveal to them their own. ~ Benjamin Disraeli",
    "The only limit to our realization of tomorrow will be our doubts of today. ~ Franklin D. Roosevelt",
    "If we are not fully ourselves, truly in the present moment, we miss everything. ~ Thích Nhất Hạnh",
    "Well done is better than well said. ~ Benjamin Franklin",
    "Friendship may, and often does, grow into love, but love never subsides into friendship. ~ Lord Byron",
    "Myths which are believed in tend to become true. ~ George Orwell",
    "One today is worth two tomorrows. ~ Benjamin Franklin",
    "Life shrinks or expands in proportion to one's courage. ~ Anaïs Nin",
    "Everything has beauty, but not everyone sees it. ~ Confucius",
    "A man may fulfil the object of his existence by asking a question he cannot answer, and attempting a task he cannot achieve. ~ Oliver Wendell Holmes Jr.",
    "Go for it now. The future is promised to no one. ~ Wayne Dyer",
    "Make the most of yourself, for that is all there is of you. ~ Ralph Waldo Emerson",
    "To go against the dominant thinking of your friends, of most of the people you see every day, is perhaps the most difficult act of heroism you can perform. ~ Theodore H. White",
    "They must often change, who would be constant in happiness or wisdom. ~ Confucius",
    "You win the victory when you yield to friends. ~ Sophocles",
    "If you wish to be a writer, write. ~ Epictetus",
    "All that is necessary is to accept the impossible, do without the indispensable, and bear the intolerable. ~ Kathleen Norris",
    "This is the final test of a gentleman: his respect for those who can be of no possible value to him. ~ William Lyon Phelps",
    "Wherever you go, go with all your heart. ~ Confucius",
    "If you have made mistakes, there is always another chance for you. You may have a fresh start any moment you choose. ~ Mary Pickford",
    "The best preparation for tomorrow is doing your best today. ~ H. Jackson Brown Jr.",
    "Can you imagine what I would do if I could do all I can? ~ Sun Tzu",
    "Good timber does not grow with ease; the stronger the wind, the stronger the trees. ~ J. Willard Marriott",
    "Without passion man is a mere latent force and possibility, like the flint which awaits the shock of the iron before it can give forth its spark. ~ Henri-Frédéric Amiel",
    "To make no mistakes is not in the power of man; but from their errors and mistakes the wise and good learn wisdom for the future. ~ Plutarch",
    "Promises are the uniquely human way of ordering the future, making it predictable and reliable to the extent that this is humanly possible. ~ Hannah Arendt",
    "Formula for success: under promise and over deliver. ~ Tom Peters",
    "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world. ~ Harriet Tubman",
    "Consider that not only do negative thoughts and emotions destroy our experience of peace, they also undermine our health. ~ Dalai Lama",
    "Those that know, do. Those that understand, teach. ~ Aristotle",
    "There is nothing happens to any person but what was in his power to go through with. ~ Marcus Aurelius",
    "The invariable mark of wisdom is to see the miraculous in the common. ~ Ralph Waldo Emerson",
    "Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them. ~ William Shakespeare",
    "And when the world is created, it is created in such a way that those eternal objects of God's loving wisdom become actualities - interacting with one another, relating to God in the finite realm. ~ Rowan Williams",
    "Accept challenges, so that you may feel the exhilaration of victory. ~ George S. Patton",
    "He who learns must suffer. And even in our sleep pain that cannot forget falls drop by drop upon the heart, and in our own despair, against our will, comes wisdom to us by the awful grace of God. ~ Aeschylus",
    "Never idealize others. They will never live up to your expectations. ~ Leo Buscaglia",
    "Good people are good because they've come to wisdom through failure. We get very little wisdom from success, you know. ~ William Saroyan",
    "He that respects himself is safe from others; he wears a coat of mail that none can pierce. ~ Henry Wadsworth Longfellow",
    "Learning without reflection is a waste, reflection without learning is dangerous. ~ Confucius",
    "Life is movement-we breathe, we eat, we walk, we move! ~ John Pierrakos",
    "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step. ~ Laozi",
    "Ignorant men don't know what good they hold in their hands until they've flung it away. ~ Sophocles",
    "Work while you have the light. You are responsible for the talent that has been entrusted to you. ~ Henri-Frédéric Amiel",
    "In action a great heart is the chief qualification. In work, a great head. ~ Arthur Schopenhauer",
    "The world makes way for the man who knows where he is going. ~ Ralph Waldo Emerson",
    "Do what you can. Want what you have. Be who you are. ~ Forrest Church",
    "Wisdom and penetration are the fruit of experience, not the lessons of retirement and leisure. Great necessities call out great virtues. ~ Abigail Adams",
    "The cautious seldom err. ~ Confucius",
    "There is nothing on this earth more to be prized than true friendship. ~ Thomas Aquinas",
    "In a controversy the instant we feel anger we have already ceased striving for the truth, and have begun striving for ourselves. ~ Buddha",
    "Action is eloquence! ~ William Shakespeare",
    "I love you the more in that I believe you had liked me for my own sake and for nothing else. ~ John Keats",
    "Be like the flower, turn your face to the sun. ~ Kahlil Gibran",
    "Science gives us knowledge, but only philosophy can give us wisdom. ~ Will Durant",
    "Nothing is at last sacred but the integrity of your own mind. ~ Ralph Waldo Emerson",
    "Life has no blessing like a prudent friend. ~ Euripides",
    "So much technology, so little talent. ~ Vernor Vinge",
    "When you judge another, you do not define them, you define yourself. ~ Wayne Dyer",
    "All men have a sweetness in their life. That is what helps them go on. It is towards that they turn when they feel too worn out. ~ Albert Camus",
    "It requires wisdom to understand wisdom: the music is nothing if the audience is deaf. ~ Walter Lippmann",
    "Weve got to have a dream if we are going to make a dream come true. ~ Walt Disney",
    "The more sand that has escaped from the hourglass of our life, the clearer we should see through it. ~ Jean-Paul Sartre",
    "The only thing to do with good advice is to pass it on. It is never of any use to oneself. ~ Oscar Wilde",
    "It is impossible to love and to be wise. ~ Francis Bacon",
    "No distance of place or lapse of time can lessen the friendship of those who are thoroughly persuaded of each other's worth. ~ Robert Southey",
    "Reality is merely an illusion, albeit a very persistent one. ~ Albert Einstein",
    "It is on our failures that we base a new and different and better success. ~ Havelock Ellis",
    "The sincere friends of this world are as ship lights in the stormiest of nights. ~ Giotto",
    "There are basically two types of people. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded. ~ Mark Twain",
    "Friendship is the source of the greatest pleasures, and without friends even the most agreeable pursuits become tedious. ~ Thomas Aquinas",
    "Do not be too timid and squeamish about your reactions. All life is an experiment. The more experiments you make the better. ~ Ralph Waldo Emerson",
    "If there is such a thing as a good marriage, it is because it resembles friendship rather than love. ~ Michel de Montaigne",
    "Chance is always powerful. Let your hook be always cast; in the pool where you least expect it, there will be a fish. ~ Ovid",
    "First say to yourself what you would be; and then do what you have to do. ~ Epictetus",
    "You, yourself, as much as anybody in the entire universe, deserve your love and affection. ~ Buddha",
    "The road of excess leads to the palace of wisdom. ~ William Blake",
    "Holy wisdom confounds Satan and all his wickednesses. ~ Francis of Assisi",
    "You have to do your own growing no matter how tall your grandfather was. ~ Abraham Lincoln",
    "Always remember that you are absolutely unique. Just like everyone else. ~ Margaret Mead",
    "Your talent is God's gift to you. What you do with it is your gift back to God. ~ Leo Buscaglia",
    "If I know what love is, it is because of you. ~ Hermann Hesse",
    "Courage is not the absence of fear, but simply moving on with dignity despite that fear. ~ Pat Riley",
    "Our shared values define us more than our differences. And acknowledging those shared values can see us through our challenges today if we have the wisdom to trust in them again. ~ John McCain",
    "He that never changes his opinions, never corrects his mistakes, and will never be wiser on the morrow than he is today. ~ Tryon Edwards",
    "To fly, we have to have resistance. ~ Maya Lin",
    "It is not so important to know everything as to appreciate what we learn. ~ Hannah More",
    "Between saying and doing, many a pair of shoes is worn out. ~ Iris Murdoch",
    "What we see depends mainly on what we look for. ~ John Lubbock",
    "Loss is nothing else but change,and change is Natures delight. ~ Marcus Aurelius",
    "There is a difference between happiness and wisdom: he that thinks himself the happiest man is really so; but he that thinks himself the wisest is generally the greatest fool. ~ Francis Bacon",
    "When the solution is simple, God is answering. ~ Albert Einstein",
    "Four steps to achievement: Plan purposefully. Prepare prayerfully. Proceed positively. Pursue persistently. ~ William Arthur Ward",
    "Keep silence for the most part, and speak only when you must, and then briefly. ~ Epictetus",
    "To give ones self earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom. ~ Confucius",
    "The cause is hidden. The effect is visible to all. ~ Ovid",
    "There is only one success - to be able to spend your life in your own way. ~ Christopher Morley",
    "The only journey is the one within. ~ Rainer Maria Rilke",
    "All human wisdom is summed up in two words; wait and hope. ~ Alexandre Dumas",
    "When people are like each other they tend to like each other. ~ Tony Robbins",
    "Study the past, if you would divine the future. ~ Confucius",
    "To bring anything into your life, imagine that it's already there. ~ Richard Bach",
    "There are two primary choices in life: to accept conditions as they exist, or accept responsibility for changing them. ~ Denis Waitley",
    "In wisdom gathered over time I have found that every experience is a form of exploration. ~ Ansel Adams",
    "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. ~ Marie Curie",
    "Im not in this world to live up to your expectations and you're not in this world to live up to mine. ~ Bruce Lee",
    "It has become appallingly obvious that our technology has exceeded our humanity. ~ Albert Einstein",
    "An ant on the move does more than a dozing ox ~ Laozi",
    "The Superior Man is aware of Righteousness, the inferior man is aware of advantage. ~ Confucius",
    "Never promise more than you can perform. ~ Publilius Syrus",
    "Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence. ~ George Washington",
    "Keep yourself to the sunshine and you cannot see the shadow. ~ Helen Keller",
    "Life is a learning experience, only if you learn. ~ Yogi Berra",
    "All difficult things have their origin in that which is easy, and great things in that which is small. ~ Laozi",
    "The past has no power to stop you from being present now. Only your grievance about the past can do that. ~ Eckhart Tolle",
    "If a man does his best, what else is there? ~ George S. Patton",
    "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy. ~ Thích Nhất Hạnh",
    "I believe that we are fundamentally the same and have the same basic potential. ~ Dalai Lama",
    "Everything you are against weakens you. Everything you are for empowers you. ~ Wayne Dyer",
    "The smallest act of kindness is worth more than the grandest intention. ~ Oscar Wilde",
    "I never worry about action, but only inaction. ~ Winston Churchill",
    "Discipline is the bridge between goals and accomplishment. ~ Jim Rohn",
    "Read as you taste fruit or savor wine, or enjoy friendship, love or life. ~ George Herbert",
    "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. ~ Dale Carnegie",
    "A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them. ~ John C. Maxwell",
    "I destroy my enemies when I make them my friends. ~ Abraham Lincoln",
    "So is cheerfulness, or a good temper, the more it is spent, the more remains. ~ Ralph Waldo Emerson",
    "All children are artists. The problem is how to remain an artist once he grows up. ~ Pablo Picasso",
    "Difficulties increase the nearer we get to the goal. ~ Johann Wolfgang von Goethe",
    "Where is the Life we have lost in living? Where is the wisdom we have lost in knowledge? Where is the knowledge we have lost in information? ~ George Eliot",
    "Be the chief but never the lord. ~ Laozi",
    "There is no friendship, no love, like that of the parent for the child. ~ Henry Ward Beecher",
    "Trust only movement. Life happens at the level of events, not of words. Trust movement. ~ Alfred Adler",
    "Wisdom has never made a bigot, but learning has. ~ Josh Billings",
    "The awareness of our own strength makes us modest. ~ Paul Cézanne",
    "Cherish your visions and your dreams as they are the children of your soul; the blueprints of your ultimate achievements. ~ Napoleon Hill",
    "A man is great by deeds, not by birth. ~ Chanakya",
    "You must do the things you think you cannot do. ~ Eleanor Roosevelt",
    "You will not be punished for your anger, you will be punished by your anger. ~ Buddha",
    "Nobody made a greater mistake than he who did nothing because he could do only a little. ~ Edmund Burke",
    "Happiness is not something ready made. It comes from your own actions. ~ Dalai Lama",
    "The truest wisdom is a resolute determination. ~ Napoleon",
    "I find hope in the darkest of days, and focus in the brightest. I do not judge the universe. ~ Dalai Lama",
    "If we could see the miracle of a single flower clearly, our whole life would change. ~ Buddha",
    "The meaning I picked, the one that changed my life: Overcome fear, behold wonder. ~ Richard Bach",
    "You can't cross the sea merely by standing and staring at the water. ~ Rabindranath Tagore",
    "If you set out to be liked, you would be prepared to compromise on anything at any time, and you would achieve nothing. ~ Margaret Thatcher",
    "Doing what you love is the cornerstone of having abundance in your life. ~ Wayne Dyer",
    "Do good by stealth, and blush to find it fame. ~ Alexander Pope",
    "When you dance, your purpose is not to get to a certain place on the floor. It's to enjoy each step along the way. ~ Wayne Dyer",
    "Before you put on a frown, make absolutely sure there are no smiles available. ~ James M. Beggs",
    "Technology… the knack of so arranging the world that we don't have to experience it. ~ Max Frisch",
    "A garden is always a series of losses set against a few triumphs, like life itself. ~ May Sarton",
    "Mind is everything: muscle, pieces of rubber. All that I am, I am because of my mind. ~ Paavo Nurmi",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path. ~ Buddha",
    "Listen to what you know instead of what you fear. ~ Richard Bach",
    "Problems are only opportunities with thorns on them. ~ Hugh Miller",
    "Wisdom comes alone through suffering. ~ Aeschylus",
    "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them. ~ John F. Kennedy",
    "A passion for politics stems usually from an insatiable need, either for power, or for friendship and adulation, or a combination of both. ~ Fawn M. Brodie",
    "Your vision will become clear only when you look into your heart. Who looks outside, dreams. Who looks inside, awakens. ~ Carl Jung",
    "Genius unrefined resembles a flash of lightning, but wisdom is like the sun. ~ Franz Grillparzer",
    "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek. ~ Barack Obama",
    "Let my skin and sinews and bones dry up, together with all the flesh and blood of my body! I welcome it! But I will not move from this spot until I have attained the supreme and final wisdom. ~ Buddha",
    "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world. ~ Archimedes",
    "Quick decisions are unsafe decisions. ~ Sophocles",
    "At the center of your being you have the answer; you know who you are and you know what you want. ~ Laozi",
    "Technology has to be invented or adopted. ~ Jared Diamond",
    "Reason and free inquiry are the only effectual agents against error. ~ Thomas Jefferson",
    "Fine words and an insinuating appearance are seldom associated with true virtue ~ Confucius",
    "If you're walking down the right path and you're willing to keep walking, eventually you'll make progress. ~ Barack Obama",
    "Friendship, like credit, is highest when it is not used. ~ Elbert Hubbard",
    "You cannot travel the path until you have become the path itself. ~ Buddha",
    "There are no failures. Just experiences and your reactions to them. ~ Tom Krause",
    "Remember that sometimes not getting what you want is a wonderful stroke of luck. ~ Dalai Lama",
    "Technology frightens me to death. It's designed by engineers to impress other engineers. And they always come with instruction booklets that are written by engineers for other engineers — which is why almost no technology ever works. ~ John Cleese",
    "He who lives in harmony with himself lives in harmony with the world. ~ Marcus Aurelius",
    "The superior man is modest in his speech, but exceeds in his actions. ~ Confucius",
    "The doorstep to the temple of wisdom is a knowledge of our own ignorance. ~ Benjamin Franklin",
    "It is better to understand a little than to misunderstand a lot. ~ Anatole France",
    "It always seems impossible until it's done. ~ Nelson Mandela",
    "When we seek to discover the best in others, we somehow bring out the best in ourselves. ~ William Arthur Ward",
    "To wear your heart on your sleeve isn't a very good plan; you should wear it inside, where it functions best. ~ Margaret Thatcher",
    "All love that has not friendship for its base, is like a mansion built upon the sand. ~ Ella Wheeler Wilcox",
    "The strong bond of friendship is not always a balanced equation; friendship is not always about giving and taking in equal shares. Instead, friendship is grounded in a feeling that you know exactly who will be there for you when you need something, no matter what or when. ~ Simon Sinek",
    "Bodily exercise, when compulsory, does no harm to the body; but knowledge which is acquired under compulsion obtains no hold on the mind. ~ Plato",
    "Life is really simple, but we insist on making it complicated. ~ Confucius",
    "Friendship multiplies the good of life and divides the evil. ~ Baltasar Gracián",
    "Every artist dips his brush in his own soul, and paints his own nature into his pictures. ~ Henry Ward Beecher",
    "Always be mindful of the kindness and not the faults of others. ~ Buddha",
    "Forgiveness is that subtle thread that binds both love and friendship. Without forgiveness, you may not even have a child one day. ~ George Foreman",
    "The difference between what we do and what we are capable of doing would suffice to solve most of the worlds problems. ~ Mahatma Gandhi",
    "Love all, trust a few, do wrong to none. ~ William Shakespeare",
    "Hope arouses, as nothing else can arouse, a passion for the possible. ~ William Sloane Coffin",
    "He is able who thinks he is able. ~ Buddha",
    "Time stays long enough for anyone who will use it. ~ Leonardo da Vinci",
    "Even if you're on the right track, you'll get run over if you just sit there. ~ Will Rogers",
    "Know that although in the eternal scheme of things you are small, you are also unique and irreplaceable, as are all your fellow humans everywhere in the world. ~ Margaret Laurence",
    "Man is not sum of what he has already, but rather the sum of what he does not yet have, of what he could have. ~ Jean-Paul Sartre",
    "To free us from the expectations of others, to give us back to ourselves... there lies the great, singular power of self-respect. ~ Joan Didion",
    "Never reach out your hand unless you're willing to extend an arm. ~ Pope Paul VI",
    "I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than You, and keep doing what you love. Do what you love, and you will find the way to get it out to the world. ~ Judy Collins",
    "Friendship is Love without his wings! ~ Lord Byron",
    "The thought manifests as the word. The word manifests as the deed. The deed develops into habit. And the habit hardens into character. ~ Buddha",
    "We never understand how little we need in this world until we know the loss of it. ~ J. M. Barrie",
    "Imagination is the living power and prime agent of all human perception. ~ Samuel Taylor Coleridge",
    "The greatest way to live with honor in this world is to be what we pretend to be. ~ Socrates",
    "The secret of getting ahead is getting started. ~ Mark Twain",
    "Wisdom begins at the end. ~ Daniel Webster",
    "The least of things with a meaning is worth more in life than the greatest of things without it. ~ Carl Jung",
    "Love demands infinitely less than friendship. ~ George Jean Nathan",
    "Wisdom is oftentimes nearer when we stoop than when we soar. ~ William Wordsworth",
    "No snowflake in an avalanche ever feels responsible. ~ Voltaire",
    "In life, all good things come hard, but wisdom is the hardest to come by. ~ Lucille Ball",
    "Communications tools don't get socially interesting until they get technologically boring. ~ Clay Shirky",
    "Until you value yourself, you won't value your time. Until you value your time, you won't do anything with it. ~ M. Scott Peck",
    "Small opportunities are often the beginning of great enterprises. ~ Demosthenes",
    "I hear and I forget. I see and I remember. I do and I understand. ~ Confucius",
    "Wise men talk because they have something to say; fools, because they have to say something. ~ Plato",
    "One's philosophy is not best expressed in words; it is expressed in the choices one makes... and the choices we make are ultimately our responsibility. ~ Eleanor Roosevelt",
    "Of course there is no formula for success except perhaps an unconditional acceptance of life and what it brings. ~ Arthur Rubinstein",
    "Great ideas often receive violent opposition from mediocre minds. ~ Albert Einstein",
    "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. ~ Audre Lorde",
    "Learn from yesterday, live for today, hope for tomorrow. ~ Albert Einstein",
    "When you doubt your power, you give power to your doubt. ~ Honoré de Balzac",
    "When I let go of what I am, I become what I might be. ~ Laozi",
    "Don't cry because it's over. Smile because it happened. ~ Dr. Seuss",
    "The more man meditates upon good thoughts, the better will be his world and the world at large. ~ Confucius",
    "The aim of life is self-development. To realize ones nature perfectly - that is what each of us is here for. ~ Oscar Wilde",
    "You can always tell a real friend: when you've made a fool of yourself he doesn't feel you've done a permanent job. ~ Laurence J. Peter",
    "Everything that irritates us about others can lead us to a better understanding of ourselves. ~ Carl Jung",
    "It is very easy to forgive others their mistakes; it takes more grit to forgive them for having witnessed your own. ~ Jessamyn West",
    "Wisdom, compassion, and courage are the three universally recognized moral qualities of men. ~ Confucius",
    "The universe is full of magical things, patiently waiting for our wits to grow sharper. ~ Eden Phillpotts",
    "I have no special talent. I am only passionately curious. ~ Albert Einstein",
    "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them? ~ Buddha",
    "I love my past. I love my present. Im not ashamed of what Ive had, and Im not sad because I have it no longer. ~ Colette",
    "To fly as fast as thought, you must begin by knowing that you have already arrived. ~ Richard Bach",
    "Not what we have but what we enjoy constitutes our abundance. ~ Jean Antoine Petit-Senn",
    "Be not angry that you cannot make others as you wish them to be, since you cannot make yourself as you wish to be. ~ Thomas à Kempis",
    "No act of kindness, no matter how small, is ever wasted. ~ Aesop",
    "If you aren't going all the way, why go at all? ~ Joe Namath",
    "The more you know yourself, the more you forgive yourself. ~ Confucius",
    "Don't wait. The time will never be just right. ~ Napoleon Hill",
    "The way you see people is the way you treat them, and the way you treat them is what they become. ~ Johann Wolfgang von Goethe",
    "You are a product of your environment. So choose the environment that will best develop you toward your objective. Analyze your life in terms of its environment. Are the things around you helping you toward success - or are they holding you back? ~ W. Clement Stone",
    "There is no charm equal to tenderness of heart. ~ Jane Austen",
    "Love cures people - both the ones who give it and the ones who receive it. ~ Karl Menninger",
    "Those who dare to fail miserably can achieve greatly. ~ John F. Kennedy",
    "The only real valuable thing is intuition. ~ Albert Einstein",
    "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear. ~ Buddha",
    "It is more shameful to distrust our friends than to be deceived by them. ~ Confucius",
    "The only limit to your impact is your imagination and commitment. ~ Tony Robbins",
    "The poor man is not he who is without a cent, but he who is without a dream. ~ Harry Kemp",
    "Friendship is the marriage of the soul, and this marriage is liable to divorce. ~ Voltaire",
    "It is better to have enough ideas for some of them to be wrong, than to be always right by having no ideas at all. ~ Edward de Bono",
    "He who talks more is sooner exhausted. ~ Laozi",
    "If you love life, don't waste time, for time is what life is made up of. ~ Bruce Lee",
    "The wisest men follow their own direction. ~ Euripides",
    "If you do what you've always done, you'll get what youve always gotten. ~ Tony Robbins",
    "I define friendship as a bond that transcends all barriers. When you are ready to expect anything and everything from friends, good, bad or ugly... that's what I call true friendship. ~ Harbhajan Singh",
    "If you seek truth you will not seek victory by dishonourable means, and if you find truth you will become invincible. ~ Epictetus",
    "The pain passes, but the beauty remains. ~ Pierre-Auguste Renoir",
    "Yesterdays home runs don't win today's games. ~ Babe Ruth",
    "Never mistake motion for action. ~ Ernest Hemingway",
    "Trust yourself. You know more than you think you do. ~ Benjamin Spock",
    "There is only one corner of the universe you can be certain of improving, and that's your own self. ~ Aldous Huxley",
    "A life spent making mistakes is not only more honourable, but more useful than a life spent doing nothing. ~ George Bernard Shaw",
    "I never see what has been done; I only see what remains to be done. ~ Marie Curie",
    "Marriage: A friendship recognized by the police. ~ Robert Louis Stevenson",
    "Every one in the world ought to do the things for which he is specially adapted. It is the part of wisdom to recognize what each one of us is best fitted for, and it is the part of education to perfect and utilize such predispositions. Because education can direct and aid nature but can never transform her. ~ Maria Montessori",
    "A hero is no braver than an ordinary man, but he is braver five minutes longer. ~ Ralph Waldo Emerson",
    "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins. ~ Jim Rohn",
    "I will prepare and some day my chance will come. ~ Abraham Lincoln",
    "Love is never lost. If not reciprocated, it will flow back and soften and purify the heart. ~ Washington Irving",
    "Wisdom is the power to put our time and our knowledge to the proper use. ~ Thomas J. Watson",
    "What is new in the world? Nothing. What is old in the world? Nothing. Everything has always been and will always be. ~ Sai Baba",
    "Anybody can make history. Only a great man can write it. ~ Oscar Wilde",
    "Know what's important and what isn't. Have the wisdom to know the right thing to do, the integrity to do it, the character to stand up to those who don't, and the courage to stop those who won't. ~ Mark Goulston",
    "A really great talent finds its happiness in execution. ~ Johann Wolfgang von Goethe",
    "The world has the habit of making room for the man whose actions show that he knows where he is going. ~ Napoleon Hill",
    "Wrinkles should merely indicate where smiles have been. ~ Mark Twain",
    "There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered. ~ Nelson Mandela",
    "Any sufficiently advanced technology is equivalent to magic. ~ Arthur C. Clarke",
    "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it. ~ Michelangelo",
    "Respect should be earned by actions, and not acquired by years. ~ Frank Lloyd Wright",
    "We cannot do everything at once, but we can do something at once. ~ Calvin Coolidge",
    "The art of storytelling is reaching its end because the epic side of truth, wisdom, is dying out. ~ Walter Benjamin",
    "The heart has its reasons which reason knows not of. ~ Blaise Pascal",
    "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow. ~ Melody Beattie",
    "I cannot give you the formula for success, but I can give you the formula for failure: which is: Try to please everybody. ~ Herbert Bayard Swope",
    "Anyone who doesn't take truth seriously in small matters cannot be trusted in large ones either. ~ Albert Einstein",
    "Our distrust is very expensive. ~ Ralph Waldo Emerson",
    "When you see a good person, think of becoming like him. When you see someone not so good, reflect on your own weak points. ~ Confucius",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. ~ Thomas Edison",
    "There is nothing so useless as doing efficiently that which should not be done at all. ~ Peter Drucker",
    "He who is taught to live upon little owes more to his father's wisdom than he who has a great deal left him does to his father's care. ~ William C. Menninger",
    "The differences between friends cannot but reinforce their friendship. ~ Mao Zedong",
    "One must be fond of people and trust them if one is not to make a mess of life. ~ E. M. Forster",
    "I think somehow we learn who we really are and then live with that decision. ~ Eleanor Roosevelt",
    "Life is not a problem to be solved, but a reality to be experienced. ~ Søren Kierkegaard",
    "I allow my intuition to lead my path. ~ Manuel Puig",
    "A man who doesn't trust himself can never really trust anyone else. ~ Jean François Paul de Gondi",
    "What you do not want done to yourself, do not do to others. ~ Confucius",
    "If A is success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut. ~ Albert Einstein",
    "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live. ~ Mortimer J. Adler",
    "In all things of nature there is something of the marvelous. ~ Aristotle",
    "Do you want to know who you are? Don't ask. Act! Action will delineate and define you. ~ Thomas Jefferson",
    "Life isn't about finding yourself. Life is about creating yourself. ~ Bernard Shaw",
    "The less effort, the faster and more powerful you will be. ~ Bruce Lee",
    "Men in general judge more from appearances than from reality. All men have eyes, but few have the gift of penetration. ~ Niccolò Machiavelli",
    "Every problem has a gift for you in its hands. ~ Richard Bach",
    "Autumn is a second spring when every leaf is a flower. ~ Albert Camus",
    "Our greatness lies not so much in being able to remake the world as being able to remake ourselves. ~ Mahatma Gandhi",
    "Happiness is when what you think, what you say, and what you do are in harmony. ~ Mahatma Gandhi",
    "If you spend too much time thinking about a thing, you'll never get it done. ~ Bruce Lee",
    "To be aware of a single shortcoming in oneself is more useful than to be aware of a thousand in someone else. ~ Dalai Lama",
    "There never was a good knife made of bad steel. ~ Benjamin Franklin",
    "The moment one gives close attention to anything, it becomes a mysterious, awesome, indescribably magnificent world in itself. ~ Henry Miller",
    "If you have knowledge, let others light their candles in it. ~ Margaret Fuller",
    "For every failure, there's an alternative course of action. You just have to find it. When you come to a roadblock, take a detour. ~ Mary Kay Ash",
    "The right way is not always the popular and easy way. Standing for right when it is unpopular is a true test of moral character. ~ Margaret Chase Smith",
    "If we had no winter, the spring would not be so pleasant; if we did not sometimes taste of adversity, prosperity would not be so welcome. ~ Anne Bradstreet",
    "Every time you smile at someone, it is an action of love, a gift to that person, a beautiful thing. ~ Mother Teresa",
    "Mistakes are the usual bridge between inexperience and wisdom. ~ Phyllis Grissim-Theroux",
    "I have done my best: that is about all the philosophy of living one needs. ~ Lin Yutang",
    "A true friend is the most precious of all possessions and the one we take the least thought about acquiring. ~ François de La Rochefoucauld",
    "Do not follow where the path may lead. Go, instead, where there is no path and leave a trail. ~ Ralph Waldo Emerson",
    "If you don't know where you are going, any road will get you there. ~ Lewis Carroll",
    "True happiness arises, in the first place, from the enjoyment of one's self, and in the next, from the friendship and conversation of a few select companions. ~ Joseph Addison",
    "The greatest remedy for anger is delay. ~ Seneca the Younger",
    "True friends stab you in the front. ~ Oscar Wilde",
    "You must welcome change as the rule but not as your ruler. ~ Denis Waitley",
    "Constant kindness can accomplish much. As the sun makes ice melt, kindness causes misunderstanding, mistrust, and hostility to evaporate. ~ Albert Schweitzer",
    "Life is a succession of lessons, which must be lived to be understood. ~ Ralph Waldo Emerson",
    "Silence is a source of great strength. ~ Laozi",
    "Your mind will answer most questions if you learn to relax and wait for the answer. ~ William Burroughs",
    "Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict. ~ William Ellery Channing",
    "In all chaos there is a cosmos, in all disorder a secret order. ~ Carl Jung",
    "From error to error one discovers the entire truth. ~ Sigmund Freud",
    "Liberty, taking the word in its concrete sense, consists in the ability to choose. ~ Simone Weil",
    "Whoso loves, believes the impossible. ~ Elizabeth Browning",
    "What matters is the value we've created in our lives, the people we've made happy and how much we've grown as people. ~ Daisaku Ikeda",
    "As you think, so shall you become. ~ Bruce Lee",
    "This world, after all our science and sciences, is still a miracle; wonderful, inscrutable, magical and more, to whosoever will think of it. ~ Thomas Carlyle",
    "Appreciation can make a day, even change a life. Your willingness to put it into words is all that is necessary. ~ Margaret Cousins",
    "It is not only for what we do that we are held responsible, but also for what we do not do. ~ Molière",
    "Let us sacrifice our today so that our children can have a better tomorrow. ~ A. P. J. Abdul Kalam",
    "The most I can do for my friend is simply be his friend. ~ Henry David Thoreau",
    "We are all inclined to judge ourselves by our ideals; others, by their acts. ~ Harold Nicolson",
    "Do something wonderful, people may imitate it. ~ Albert Schweitzer",
    "And as we let our own light shine, we unconsciously give other people permission to do the same. ~ Nelson Mandela",
    "I'd rather regret the things I've done than regret the things I haven't done. ~ Lucille Ball",
    "All achievements, all earned riches, have their beginning in an idea. ~ Napoleon Hill",
    "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along. ~ George Herbert",
    "Success in business requires training and discipline and hard work. But if you're not frightened by these things, the opportunities are just as great today as they ever were. ~ David Rockefeller",
    "When you come to the end of your rope, tie a knot and hang on. ~ Franklin D. Roosevelt",
    "The supreme art of war is to subdue the enemy without fighting. ~ Sun Tzu",
    "Be faithful in small things because it is in them that your strength lies. ~ Mother Teresa",
    "One's friends are that part of the human race with which one can be human. ~ George Santayana",
    "No one has a finer command of language than the person who keeps his mouth shut. ~ Sam Rayburn",
    "Build a better mousetrap and the world will beat a path to your door. ~ Ralph Waldo Emerson",
    "Knowledge is going to make you stronger. Knowledge is going to let you control your life. Knowledge is going to give you the wisdom to teach their children. Knowledge is the thing that makes you smile in the face of disaster. ~ Avery Brooks",
    "Every gift from a friend is a wish for your happiness. ~ Richard Bach",
    "Never explain - your friends do not need it and your enemies will not believe you anyway. ~ Elbert Hubbard",
    "Setting an example is not the main means of influencing another, it is the only means. ~ Albert Einstein",
    "It is not the possession of truth, but the success which attends the seeking after it, that enriches the seeker and brings happiness to him. ~ Max Planck",
    "If you break your neck, if you have nothing to eat, if your house is on fire, then you got a problem. Everything else is inconvenience. ~ Robert Fulghum",
    "Sincerity is the way of Heaven. The attainment of sincerity is the way of men. ~ Confucius",
    "Pure, holy simplicity confounds all the wisdom of this world and the wisdom of the flesh. ~ Francis of Assisi",
    "To hell with circumstances; I create opportunities. ~ Bruce Lee",
    "Much wisdom often goes with fewest words. ~ Sophocles",
    "A friend is someone who gives you total freedom to be yourself. ~ Jim Morrison",
    "I can, therefore I am. ~ Simone Weil",
    "Begin, be bold, and venture to be wise. ~ Horace",
    "Always seek out the seed of triumph in every adversity. ~ Og Mandino",
    "I will give you a definition of a proud man: he is a man who has neither vanity nor wisdom one filled with hatreds cannot be vain, neither can he be wise. ~ John Keats",
    "The winds and waves are always on the side of the ablest navigators. ~ Edward Gibbon",
    "It is fatal to enter any war without the will to win it. ~ Douglas MacArthur",
    "Knowledge rests not upon truth alone, but upon error also. ~ Carl Jung",
    "A man cannot be said to succeed in this life who does not satisfy one friend. ~ Henry David Thoreau",
    "Our lives are a sum total of the choices we have made. ~ Wayne Dyer",
    "It is one of the blessings of old friends that you can afford to be stupid with them. ~ Ralph Waldo Emerson",
    "Joy is the best makeup. ~ Anne Lamott",
    "Ask yourself the secret of your success. Listen to your answer, and practice it. ~ Richard Bach",
    "It is a common experience that a problem difficult at night is resolved in the morning after the committee of sleep has worked on it. ~ John Steinbeck",
    "The things that one most wants to do are the things that are probably most worth doing. ~ Winifred Holtby",
    "When fate hands us a lemon, lets try to make lemonade. ~ Dale Carnegie",
    "All fixed set patterns are incapable of adaptability or pliability. The truth is outside of all fixed patterns. ~ Bruce Lee",
    "The smallest deed is better than the greatest intention. ~ John Burroughs",
    "Tragedy is a tool for the living to gain wisdom, not a guide by which to live. ~ Robert F. Kennedy",
    "Wherever a man may happen to turn, whatever a man may undertake, he will always end up by returning to the path which nature has marked out for him. ~ Johann Wolfgang von Goethe",
    "We need to find the courage to say NO to the things and people that are not serving us if we want to rediscover ourselves and live our lives with authenticity. ~ Barbara De Angelis",
    "America's freedom of religion, and freedom from religion, offers every wisdom tradition an opportunity to address our soul-deep needs: Christianity, Judaism, Islam, Buddhism, Hinduism, secular humanism, agnosticism and atheism among others. ~ Parker Palmer",
    "We can only learn to love by loving. ~ Iris Murdoch",
    "It is good even for old men to learn wisdom. ~ Aeschylus",
    "To be tested is good. The challenged life may be the best therapist. ~ Gail Sheehy",
    "To get the full value of joy you must have someone to divide it with. ~ Mark Twain",
    "Kind words do not cost much. Yet they accomplish much. ~ Blaise Pascal",
    "If I am not for myself, who will be for me? If I am not for others, what am I? And if not now, when? ~ Rabbi Hillel",
    "Most of the shadows of life are caused by standing in our own sunshine. ~ Ralph Waldo Emerson",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. ~ Albert Schweitzer",
    "Every person, all the events of your life are there because you have drawn them there. What you choose to do with them is up to you. ~ Richard Bach",
    "Before you can inspire with emotion, you must be swamped with it yourself. Before you can move their tears, your own must flow. To convince them, you must yourself believe. ~ Winston Churchill",
    "I'm not interested in age. People who tell me their age are silly. You're as old as you feel. ~ Elizabeth Arden",
    "I have never been hurt by anything I didn't say. ~ Calvin Coolidge",
    "There is no duty we so underrate as the duty of being happy. By being happy we sow anonymous benefits upon the world. ~ Robert Louis Stevenson",
    "A youth, when at home, should be filial and, abroad, respectful to his elders. He should be earnest and truthful. He should overflow in love to all and cultivate the friendship of the good. When he has time and opportunity, after the performance of these things, he should employ them in polite studies. ~ Confucius",
    "We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly. ~ Sam Keen",
    "Lose an hour in the morning, and you will spend all day looking for it. ~ Richard Whately",
    "Remember always that you not only have the right to be an individual, you have an obligation to be one. ~ Eleanor Roosevelt",
    "I decided that it was not wisdom that enabled poets to write their poetry, but a kind of instinct or inspiration, such as you find in seers and prophets who deliver all their sublime messages without knowing in the least what they mean. ~ Isocrates",
    "True friendship multiplies the good in life and divides its evils. Strive to have friends, for life without friends is like life on a desert island... to find one real friend in a lifetime is good fortune; to keep him is a blessing. ~ Baltasar Gracián",
    "Life's most persistent and urgent question is, 'What are you doing for others?' ~ Martin Luther King Jr.",
    "No man was ever wise by chance. ~ Seneca the Younger",
    "There are two kinds of failures: those who thought and never did, and those who did and never thought. ~ Laurence J. Peter",
    "You can stand tall without standing on someone. You can be a victor without having victims. ~ Harriet Woods",
    "The more you like yourself, the less you are like anyone else, which makes you unique. ~ Walt Disney",
    "True knowledge exists in knowing that you know nothing. ~ Isocrates",
    "We shall never know all the good that a simple smile can do. ~ Mother Teresa",
    "The best thing in every noble dream is the dreamer... ~ Moncure D. Conway",
    "To succeed, we must first believe that we can. ~ Michael Korda",
    "You cannot step twice into the same river, for other waters are continually flowing in. ~ Heraclitus",
    "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart. ~ Marcus Aurelius",
    "We aim above the mark to hit the mark. ~ Ralph Waldo Emerson",
    "Some people go to priests; others to poetry; I to my friends. ~ Virginia Woolf",
    "He is no fool who gives what he cannot keep to gain what he cannot lose. ~ Jim Elliot",
    "Kindness is the golden chain by which society is bound together. ~ Johann Wolfgang von Goethe",
    "A tree is known by its fruit; a man by his deeds. A good deed is never lost; he who sows courtesy reaps friendship, and he who plants kindness gathers love. ~ Basil of Caesarea",
    "Nothing ever goes away until it has taught us what we need to know. ~ Pema Chödrön",
    "To dare is to lose ones footing momentarily. To not dare is to lose oneself. ~ Søren Kierkegaard",
    "The smallest flower is a thought, a life answering to some feature of the Great Whole, of whom they have a persistent intuition. ~ Honoré de Balzac",
    "Life is like a sewer. What you get out of it depends on what you put into it. ~ Tom Lehrer",
    "We make a living by what we get, but we make a life by what we give. ~ Winston Churchill",
    "Time you enjoyed wasting was not wasted. ~ John Lennon",
    "Neatness begets order; but from order to taste there is the same difference as from taste to genius, or from love to friendship. ~ Johann Kaspar Lavater",
    "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward. ~ Amelia Earhart",
    "No one can make you feel inferior without your consent. ~ Eleanor Roosevelt",
    "There is never enough time to do everything, but there is always enough time to do the most important thing. ~ Brian Tracy",
    "If you change the way you look at things, the things you look at change. ~ Wayne Dyer",
    "In the depth of winter, I finally learned that there was within me an invincible summer. ~ Albert Camus",
    "If you're trying to achieve, there will be roadblocks. I've had them; everybody has had them. But obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it. ~ Michael Jordan",
    "Two persons cannot long be friends if they cannot forgive each other's little failings. ~ Jean de La Bruyère",
    "All of our technology is completely unnecessary to a happy life. ~ Tom Hodgkinson",
    "Wisdom is found only in truth. ~ Johann Wolfgang von Goethe",
    "It is only the great hearted who can be true friends. The mean and cowardly, Can never know what true friendship means. ~ Charles Kingsley",
    "Absence makes the heart grow fonder. ~ Thomas Haynes Bayly",
    "If you want to go east, don't go west. ~ Ramakrishna",
    "Blessed is the man who expects nothing, for he shall never be disappointed. ~ Alexander Pope",
    "The most complicated achievements of thought are possible without the assistance of consciousness. ~ Sigmund Freud",
    "Arriving at one point is the starting point to another. ~ John Dewey",
    "Think for yourselves and let others enjoy the privilege to do so too. ~ Voltaire",
    "The only real mistake is the one from which we learn nothing. ~ John Powell",
    "The possibilities are numerous once we decide to act and not react. ~ George Bernard Shaw",
    "If a man does not make new acquaintances as he advances through life, he will soon find himself left alone. A man, sir, should keep his friendship in a constant repair. ~ Samuel Johnson",
    "Whoever is happy will make others happy, too. ~ Mark Twain",
    "When we feel love and kindness toward others, it not only makes others feel loved and cared for, but it helps us also to develop inner happiness and peace. ~ Dalai Lama",
    "Opportunity often comes disguised in the form of misfortune, or temporary defeat. ~ Napoleon Hill",
    "I am like a falling star who has finally found her place next to another in a lovely constellation, where we will sparkle in the heavens forever. ~ Amy Tan",
    "He who knows, does not speak. He who speaks, does not know. ~ Laozi",
    "The greatest minds are capable of the greatest vices as well as of the greatest virtues. ~ René Descartes",
    "Friendship is always a sweet responsibility, never an opportunity. ~ Kahlil Gibran",
    "If you accept the expectations of others, especially negative ones, then you never will change the outcome. ~ Michael Jordan",
    "Forgiveness is choosing to love. It is the first skill of self-giving love. ~ Mahatma Gandhi",
    "Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity. ~ George S. Patton",
    "Friendship needs no words - it is solitude delivered from the anguish of loneliness. ~ Dag Hammarskjöld",
    "The only real failure in life is not to be true to the best one knows. ~ Buddha",
    "Kind words can be short and easy to speak, but their echoes are truly endless. ~ Mother Teresa",
    "Loyalty and friendship, which is to me the same, created all the wealth that I've ever thought I'd have. ~ Ernie Banks",
    "The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary. ~ Thomas Edison",
    "Happiness is a perfume you cannot pour on others without getting a few drops on yourself. ~ Ralph Waldo Emerson",
    "It's important to know that words don't move mountains. Work, exacting work moves mountains. ~ Danilo Dolci",
];

pub fn get_quote(db: &mut PickleDb) -> String {
    if let Some(current_quote_count) = db.get::<usize>("quote") {
        if let Some(quote) = QUOTES.get(&current_quote_count + 1) {
            let _set = db.set("quote", &(current_quote_count + 1));
            (*quote).to_string()
        } else {
            let _set = db.set("quote", &0);
            QUOTES[0].to_string()
        }
    } else {
        let _set = db.set("quote", &0);
        QUOTES[0].to_string()
    }
}
